### PR TITLE
bar: add WithSpinner option

### PR DESCRIPTION
**Pull request by greut**
#29 ~ mpb is great for showing many tasks at once, but sometimes those tasks are unknown. For the time being we are faking the loading with a fake ETA.

https://asciinema.org/a/1VbZgh5uuY2thL1AWkddBpfPi

### CODE REVIEW

**Comment by vbauerster** [comment]
Thank you for your contribution! What if user wants to combine bar and spinner at the same time? I know such combination may look ugly, but I'd like to have such option. Will look this weekend...

**Comment by mathieu-aubin** [comment]
how come is the 'time to go/time remaning' so far away from the spinner? Wouldn't it be better to have them closer in order to keep the user's eyes sane? I mean, keep focus at the same area at least

Just commenting on what ive seen from the asciicast

**Comment by mathieu-aubin** [comment]
Also, a more typical/generic spinner could be "/|\\-/|\\-", in case you wanted to add a couple styles. Ansi blocks could also be an idea.

**Comment by vbauerster** [comment]
@mathieu-aubin , check [spinner](https://github.com/vbauerster/mpb/blob/master/examples/spinner/main.go) example, it's possible to reduce width and align the spinner.

**Comment by greut** [comment]
@vbauerster :1st_place_medal: brilliant! many thanks.

**Pull request merged**
