### PR TITLE
Fix Stderr not wokring via Output Method

### PR DESCRIPTION
**Pull request by vegh1010**

### CODE REVIEW

**Comment by vbauerster** [comment]
Can you please justify your PR? Is [func Output(w io.Writer) ProgressOption](https://godoc.org/github.com/vbauerster/mpb#Output) doesn't work for you?

**Comment by vegh1010** [comment]
Yes.  func Output(w io.Writer) ProgressOption does not seem to be working properly. I tried using mpb.Output(os.Stderr) in mpb.New() but it's not overriding cwriter value in config.

**Comment by vbauerster** [comment]
Well it works in my environment (MacOs and iTerm). When I go run with `2> test.txt` at the end, `test.txt` gets filled, which indicates that output was overwritten from `os.Stdout` to `os.Stderr`.
Make sure you initialise bar pool properly, something like this `mpb.New(mpb.Output(os.Stderr))`.

**Comment by vegh1010** [comment]
I'll have a look more on my part. Thanks

_Sent from my Samsung SM-N910C using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Pull request closed without merging**
